# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Zhi
tagline:          'New Blog'
description:      ''
url:              https://chichou.github.io
baseurl:          /

author:
  name:           'CodeColorist'

paginate:         5

links:
  twitter:        https://twitter.com/CodeColorist
  GitHub:         https://github.com/chichou
  patreon:        https://www.patreon.com/codecolorist

gems:             [jekyll-gist, jekyll-paginate]

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-seo-tag

excerpt_separator:  '<!-- more -->'