# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            CodeColorist
tagline:          'Final Lullaby'
description:      'Close your eyes and I put us to sleep'
url:              https://chichou.github.io

author:
  name:           'CodeColorist'

paginate:         5

links:
  twitter:        https://twitter.com/CodeColorist
  GitHub:         https://github.com/chichou
  patreon:        https://www.patreon.com/codecolorist

gems:             [jekyll-gist, jekyll-paginate]

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-seo-tag

excerpt_separator:  '<!-- more -->'